//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExp.QLNH.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
